src/get_dummy_fastq.py
src/move_data_from_ena.py
src/requirements.txt

Created a script `move_data_from_ena.py` that can move the data from several sources. If given an ENA study/project accession, it will retrieve all the files and move them to the folder specified. 
This tool can be used locally (Specifying a local folder) or remotely (specifying a full s3 folder e.g. `s3://hca-whatever/xxx-f343r-ssf-csdf/`)
Please let me know if you find any bugs or you would like any improvements I didn't think of!

Created a script to move data files from ENA. Fixes #52

---

src/get_dummy_fastq.py

- Refactored "get_dummy_fastq.py" to use less dependencies and some other linting changes (not finished in that regard, though)
- Added empty "requirements.txt" to be filled with needed dependencies in the future.

Refactored script to use less dependencies. Added requirements.txt

---

docs/SOPs/geo_to_hca_SOP.md

Added the documentation for the geo_to_hca toolset.

Added documentation for geo_to_hca tool. Fixes #99

---

.idea/vcs.xml
src/move_data_from_insdc.py
src/requirements.txt

Added feature to `src/move_data_from_insdc.py`:
- Now tries to search first in SRA metadata for the links to the files

Added feature to look at sra metadata to download.

---

docs/SOPs/archiving_SOP.md

Added a new SOP on `/docs/SOPs`:
- `archiving_SOP.md`
This SOP is a re-factor of the archiving steps showcased in [this document](https://docs.google.com/document/d/1S4fyCSqB3nLrCUssNMwSp6ff8tmeipMi_slnXW2Lrq4/edit?pli=1#heading=h.wzojhbhfywqr)

Created SOP for archiving

---

docs/SOPs/NCBI_SRA_cold_storage_how_to.md
docs/_config.yml

Adding a new SOP `NCBI_SRA_cold_storage_how_to.md` on how to transfer data from NCBI cold storage aws buckets using SRA cloud data delivery service.

Ncbi cloud

---

.github/ISSUE_TEMPLATE/dataset_retraction.md
docs/SOPs/data_retraction_SOP.md

Will merge to master for easy review on the [ebi-ait git pages](https://ebi-ait.github.io/hca-ebi-wrangler-central/) but will keep the branch in case more changes are needed.

Added dataset retraction SOP and template

---

docs/SOPs/archiving_SOP.md

Added clarification about AAP user/pswd

---

docs/SOPs/data_retraction_SOP.md

Added feedback to dataset retraction SOP

---

src/compare_tracker_with_nxn_sheet.py

Related to #160 
Updates to `src/compare_tracker_with_nxn_sheet.py`:
- No longer depends on hardcoded column indexes to retrieve data
- Now works by looking for specific strings in the headers (Should be easier to update in the future)
- print_output function updated to work with mapping values: Instead of hardcoding the transformations in the function, they are written in a map that ensures the transformation gets done.
Needs verification:
- @mshadbolt noticed an encoding/decoding bug with some special chars. I haven't been able to reproduce, so I don't know exactly when it happens.

Fixed column order problems. Added more information to fill.

---

src/move_data_from_insdc.py

I updated the script to include a function to retrieve files from ArrayExpress using their API to get file URLs and also included the ability to provide a file with a set of file names to limit the transfer only to these files.
I haven't fully tested but thought I would make the PR so @ESapenaVentura can review while I do final tests.

Retrieve files from ArrayExpress and provide allowed file list

---

docs/SOPs/data_retraction_SOP.md

Creating the PR to review the changes
Related to #147

Dev input for data retraction SOP

---

src/check_fastq.py
src/requirements.txt

Added new check_fastq script based on the logic from Jon's bash scri…pt but written in python and output is slightly different.
Updated requirements.txt file.

Added new check_fastq script to check fastq read lengths

---

src/check_fastq.py

Script to check fastq file read lengths.

Added input file format check

---

src/move_data_from_insdc.py

Added choice to request fastq retrieval via ena as opposed to a default, sra.

Update move data script: make database choice optional

---

docs/SOPs/hca_to_scea_tools_SOP.md

I tried to simplify the flow to make it clearer
I also moved steps we are not currently following to the 'appendix' section until/if we implement the browser functionality again

Cleaned up suitability info and deprecated steps

---

src/move_data_from_insdc.py

ebi-ait/dcp-ingest-central#190
Added some handling so that it wouldn't give a weird error.

Handle empty result from NCBI API

---

docs/SOPs/dataset_wrangling_SOP.md

Adding Contributor Matrix and Cell Type SOP together into the existing wrangling SOP

Adding Contributor Matrix and Cell Type SOP

---

.github/ISSUE_TEMPLATE/schema_priority_ticket.md
docs/SOPs/schema_update_prioritisation_SOP.md

Related to https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/408
Added schema prioritisation SOP:
- Added instruction on how to prioritise the next set of schema updates
- Added template for prioritisation ticket

Added schema updates prioritisation SOP.

---

.github/ISSUE_TEMPLATE/onboarding_process.md

For `.github/ISSUE_TEMPLATE/onboarding_process.md`:
- Fixed outdated links/references/terms

Fixed outdated links/terms. Fixes #446.

---

docs/ebi-wrangler-onboarding.md

Fixed some meetings/typos in the onboarding doc

Fixed some meetings/typos

---

docs/SOPs/dataset_acknowledgement_SOP.md

corresponding ticket: https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/382
related PR: https://github.com/ebi-ait/hca-ebi-dev-team/pull/445

ebi-ait/dcp-ingest-central#382: updated nxn.se SOP

---

docs/SOPs/NCBI_SRA_cold_storage_how_to.md

For `docs/SOPs/NCBI_SRA_cold_storage_how_to.md`:
- Added a new command to delete all files from runs that share a wildcard pattern

Added a new command to delete runs from bucket

---

docs/SOPs/contributor_communication_SOP.md
docs/SOPs/dataset_wrangling_SOP.md

ops-479 Update instructions on sending Contributor AWS keys

---

assets/plantuml_diagrams/archiving_sop.diag
docs/SOPs/archiving_SOP.md
docs/SOPs/update_ena_runs_SOP.md

ebi-ait/hca-ebi-dev-team#485
https://github.com/ebi-ait/hca-ebi-wrangler-central/blob/ops-485_update-archiving-sop/docs/SOPs/archiving_SOP.md
https://github.com/ebi-ait/hca-ebi-wrangler-central/blob/ops-485_update-archiving-sop/docs/SOPs/update_ena_runs_SOP.md

ops-485 Update Archiving SOPs

---

docs/SOPs/Globus_data_how_to.md
docs/SOPs/dataset_wrangling_SOP.md

This PR adds:
- instructions on how to get data deposited in Globus 
- links in the Wrangling SOP to the Globus and Node SOPs

Add how-to for Globus data

---

docs/SOPs/HCA_Metadata_Spreadsheet_Guide_Wranglers.md
docs/SOPs/dataset_wrangling_SOP.md

I fixed mostly links, and tried to remove some outdated information that can be confusing.
@gabsie if you want to take a look

Update miscellaneous SOP #608

---

docs/SOPs/dataset_suitability_SOP.md

This updates the Dataset suitability SOP - see [ticket](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/608) 
Let me know if I've missed anything!
@gabsie if you want to take a look

Updated eligibility criteria

---

docs/SOPs/dataset_wrangling_SOP.md
docs/SOPs/wrangling_best_practices.md

Added best practices SOP, based on the [living document](https://docs.google.com/document/d/1mz5HJ9-Irr9NOHMNZYV5xt5fwsasdULO2rrllwfFyN4/edit#heading=h.ftznwentofwm)

Added best practices SOP. Fixes #541

---

docs/ebi-wrangler-onboarding.md
src/requirements.txt

The document was already good, I've updated a few links and references.
Please add anything you think it's missing!
See [#608](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/608)

Update onboarding document

---

docs/SOPs/dataset_wrangling_SOP.md
docs/SOPs/secondary_review_SOP.md

ticket #608 
Please add anything you think would be helpful / clearer

Update SOP - secondary review and contributor account

---

docs/ebi-wrangler-onboarding.md

Add Arsenios Chatzigeorgiou to wranglers table.

Add @arschat to wranglers table

---

docs/SOPs/dataset_acknowledgement_SOP.md

Solves #867
This PR updates the instructions to run the automated import script.
Please suggest other improvements!

ops-867 Update data acknowledgment SOP

---

docs/SOPs/contributor_communication_SOP.md

Reverts ebi-ait/hca-ebi-wrangler-central#1060

Revert "Add hca-publication email template in the SOPs"

---

docs/SOPs/contributor_communication_SOP.md

Added also a no publication template by @Wkt8
Duplicate PR after accidental merge of ebi-ait/hca-ebi-wrangler-central#1060 before @ESapenaVentura review

Add HCA publication email template in the SOPs

---

.github/ISSUE_TEMPLATE/published_project_tracker.md
docs/SOPs/dataset_wrangling_SOP.md

I've added some instructions to the Wragling guide on how to wrangle to cellxgene 
Please add anything you think might be helpful!

Integrate CellxGene into wrangling flow

---

src/fill_ontologies.py

This PR :
- queries OLS
- supports the EDAM terms --> their iri still uses the data: format
- learns terms used in an array of terms and adds them to the known otologies --> this means that the same term will be used across the whole dataset for one free-text term

Improve ontology script
